// Mocks generated by Mockito 5.4.6 from annotations
// in pujangga_pos/test/features/riwayat/data/repositories/riwayat_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pujangga_pos/core/database/app_database.dart' as _i2;
import 'package:pujangga_pos/features/riwayat/data/datasources/riwayat_local_data_source.dart'
    as _i3;
import 'package:pujangga_pos/features/riwayat/data/models/riwayat_transaksi_summary_db_model.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RiwayatLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRiwayatLocalDataSource extends _i1.Mock
    implements _i3.RiwayatLocalDataSource {
  MockRiwayatLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppDatabase get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _FakeAppDatabase_0(this, Invocation.getter(#database)),
          )
          as _i2.AppDatabase);

  @override
  _i4.Future<List<_i5.RiwayatTransaksiSummaryDbModel>> getTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getTransactions, []),
            returnValue:
                _i4.Future<List<_i5.RiwayatTransaksiSummaryDbModel>>.value(
                  <_i5.RiwayatTransaksiSummaryDbModel>[],
                ),
          )
          as _i4.Future<List<_i5.RiwayatTransaksiSummaryDbModel>>);

  @override
  _i4.Future<void> voidTransaction(String? invoiceNumber) =>
      (super.noSuchMethod(
            Invocation.method(#voidTransaction, [invoiceNumber]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
